name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_index_platform
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-xdist
    
    - name: Run unit tests
      run: |
        cd backend
        pytest tests/unit/ -v --cov=app --cov-report=xml --cov-report=html --junitxml=test-results/unit-tests.xml
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_index_platform
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key
    
    - name: Run integration tests
      run: |
        cd backend
        pytest tests/integration/ -v --cov=app --cov-append --junitxml=test-results/integration-tests.xml
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_index_platform
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key
    
    - name: Run performance tests
      run: |
        cd backend
        pytest tests/performance/ -v --junitxml=test-results/performance-tests.xml -m "not slow"
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_index_platform
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key
    
    - name: Run system tests
      run: |
        cd backend
        pytest tests/system/ -v --junitxml=test-results/system-tests.xml
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_index_platform
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: backend-test-results
        path: backend/test-results/

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run unit tests
      run: |
        cd frontend
        npm run test:unit -- --coverage --watchAll=false
      env:
        CI: true
    
    - name: Run E2E tests
      run: |
        cd frontend
        npx playwright install --with-deps
        npm run test:e2e
      env:
        CI: true
    
    - name: Upload E2E test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
    
    - name: Upload E2E test videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-videos
        path: frontend/test-results/
        retention-days: 30

  security-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        cd backend
        pip install bandit safety
    
    - name: Run security scan
      run: |
        cd backend
        bandit -r app/ -f json -o security-report.json
        safety check --json --output safety-report.json
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          backend/security-report.json
          backend/safety-report.json

  load-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_index_platform
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust
    
    - name: Start application
      run: |
        cd backend
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_index_platform
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key
    
    - name: Run load tests
      run: |
        cd backend
        locust -f tests/performance/locustfile.py --headless -u 100 -r 10 -t 60s --html load-test-report.html
      env:
        TARGET_URL: http://localhost:8000
    
    - name: Upload load test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: load-test-results
        path: backend/load-test-report.html

  test-summary:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, security-tests]
    if: always()
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Generate test summary
      run: |
        echo "# Test Results Summary" > test-summary.md
        echo "" >> test-summary.md
        echo "## Backend Tests" >> test-summary.md
        if [ -f "backend-test-results/unit-tests.xml" ]; then
          echo "✅ Unit tests completed" >> test-summary.md
        else
          echo "❌ Unit tests failed" >> test-summary.md
        fi
        if [ -f "backend-test-results/integration-tests.xml" ]; then
          echo "✅ Integration tests completed" >> test-summary.md
        else
          echo "❌ Integration tests failed" >> test-summary.md
        fi
        if [ -f "backend-test-results/performance-tests.xml" ]; then
          echo "✅ Performance tests completed" >> test-summary.md
        else
          echo "❌ Performance tests failed" >> test-summary.md
        fi
        if [ -f "backend-test-results/system-tests.xml" ]; then
          echo "✅ System tests completed" >> test-summary.md
        else
          echo "❌ System tests failed" >> test-summary.md
        fi
        echo "" >> test-summary.md
        echo "## Frontend Tests" >> test-summary.md
        if [ -f "playwright-report/index.html" ]; then
          echo "✅ E2E tests completed" >> test-summary.md
        else
          echo "❌ E2E tests failed" >> test-summary.md
        fi
        echo "" >> test-summary.md
        echo "## Security Tests" >> test-summary.md
        if [ -f "security-reports/security-report.json" ]; then
          echo "✅ Security scan completed" >> test-summary.md
        else
          echo "❌ Security scan failed" >> test-summary.md
        fi
    
    - name: Comment PR with test results
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('test-summary.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });
